In [17]:
from sklearn.datasets import load_iris
import pandas as pd
iris = load_iris()
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [18]:
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [19]:
df["flower"] = iris.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  flower
0                5.1               3.5                1.4               0.2       0
1                4.9               3.0                1.4               0.2       0
2                4.7               3.2                1.3               0.2       0
3                4.6               3.1                1.5               0.2       0
4                5.0               3.6                1.4               0.2       0

In [20]:
df["flower"] = df["flower"].apply(lambda x: iris.target_names[x])
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  flower
0                5.1               3.5                1.4               0.2  setosa
1                4.9               3.0                1.4               0.2  setosa
2                4.7               3.2                1.3               0.2  setosa
3                4.6               3.1                1.5               0.2  setosa
4                5.0               3.6                1.4               0.2  setosa

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data,iris.target,test_size=0.3)

In [25]:
from sklearn.svm import SVC
model = SVC(kernel="rbf",C=30, gamma="auto")
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.9777777777777777

In [26]:
from sklearn.model_selection import cross_val_score
cross_val_score(SVC(kernel="rbf",C=30, gamma="auto"),iris.data,iris.target, cv =5)

array([0.96666667, 1.        , 0.9       , 0.93333333, 1.        ])

In [27]:
cross_val_score(SVC(kernel="linear",C=30, gamma="auto"),iris.data,iris.target, cv =5)

array([1. , 1. , 0.9, 0.9, 1. ])

In [28]:
cross_val_score(SVC(kernel="rbf",C=10, gamma="auto"),iris.data,iris.target, cv =5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [29]:
cross_val_score(SVC(kernel="linear",C=30, gamma="auto"),iris.data,iris.target, cv =5)

array([1. , 1. , 0.9, 0.9, 1. ])

In [30]:
cross_val_score(SVC(kernel="rbf",C=10, gamma="auto"),iris.data,iris.target, cv =5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [32]:
import numpy as np
kernel = ["rbf","linear"]
C = [10, 20, 30]
avg_score = {}
for kval in kernel:
    for cval in C:
        cv_score = cross_val_score(SVC(kernel=kval,C=cval, gamma="auto"),iris.data,iris.target, cv =5)
        avg_score[kval + ' ' + str(cval)] = np.average(cv_score)

avg_score

{'rbf 10': np.float64(0.9800000000000001),
 'rbf 20': np.float64(0.9666666666666668),
 'rbf 30': np.float64(0.96),
 'linear 10': np.float64(0.9733333333333334),
 'linear 20': np.float64(0.9666666666666666),
 'linear 30': np.float64(0.96)}

In [44]:
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(SVC(gamma="auto"),{
                       "C": [1,10,20], 
                   "kernel": ["rbf","linear"]
},cv=5,return_train_score=False)

clf.fit(iris.data,iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00080333, 0.0006001 , 0.00139999, 0.0010056 , 0.00120077,
        0.00099993]),
 'std_fit_time': array([4.01706443e-04, 4.89979265e-04, 7.99655971e-04, 1.33151173e-05,
        3.99425076e-04, 1.20631319e-06]),
 'mean_score_time': array([0.00079694, 0.00040002, 0.00100017, 0.00100904, 0.00059981,
        0.00080018]),
 'std_score_time': array([3.98518965e-04, 4.89920847e-04, 2.13248060e-07, 1.85178653e-05,
        4.89746360e-04, 4.00090285e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
 

In [45]:
df = pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  ...  mean_test_score  std_test_score rank_test_score
0       0.000803      0.000402         0.000797  ...         0.980000        0.016330               1
1       0.000600      0.000490         0.000400  ...         0.980000        0.016330               1
2       0.001400      0.000800         0.001000  ...         0.980000        0.016330               1
3       0.001006      0.000013         0.001009  ...         0.973333        0.038873               4
4       0.001201      0.000399         0.000600  ...         0.966667        0.036515               5
5       0.001000      0.000001         0.000800  ...         0.966667        0.042164               6

[6 rows x 15 columns]

In [46]:
df[["param_C","param_kernel","mean_test_score"]]

param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667

In [47]:
dir(clf.cv_results_)

['__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__ior__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__or__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__ror__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'clear',
 'copy',
 'fromkeys',
 'get',
 'items',
 'keys',
 'pop',
 'popitem',
 'setdefault',
 'update',
 'values']

In [48]:
clf.best_score_

np.float64(0.9800000000000001)

In [49]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [57]:
from sklearn.model_selection import RandomizedSearchCV
rs = RandomizedSearchCV(SVC(gamma="auto"),{
                       "C": [1,10,20], 
                   "kernel": ["rbf","linear"]
},cv=5,return_train_score=False,n_iter=2)

rs.fit(iris.data,iris.target)
rs.cv_results_
df = pd.DataFrame(rs.cv_results_)
df[["param_C","param_kernel","mean_test_score"]]

param_C param_kernel  mean_test_score
0       10       linear         0.973333
1        1       linear         0.980000

In [58]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [67]:
model_params = {
    'svm': {
        'model': SVC(gamma='auto'),
        'params' : {
            'C': [1,10,20],
            'kernel': ['rbf','linear']
        }  
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params' : {
            'n_estimators': [1,5,10]
        }
    },
    'logistic_regression' : {
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'params': {
            'C': [1,5,10]
        }
    }
}

In [68]:
scores = []

for model_name, mp in model_params.items():
    clf = GridSearchCV(mp["model"],mp["params"], cv=5,return_train_score=False)
    clf.fit(iris.data, iris.target)
    scores.append({
        "model": model_name,
        "best_score": clf.best_score_,
        "best_params": clf.best_params_
    })
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df
                

C:\Users\niraj.meshram\AppData\Local\miniconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
C:\Users\niraj.meshram\AppData\Local\miniconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
C:\Users\niraj.meshram\AppData\Local\miniconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
C:\Users\niraj.meshram\AppData\Local\miniconda3\Lib\site-packages\s

model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.953333        {'n_estimators': 5}
2  logistic_regression    0.966667                   {'C': 5}