In [3]:
from sklearn.datasets import load_digits
import pandas as pd
digits = load_digits()

In [4]:
X = digits.data
y = digits.target

In [31]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)

In [32]:
from sklearn.linear_model import LogisticRegression
lrmodel = LogisticRegression(max_iter=1000)
lrmodel.fit(X_train,y_train)
lrmodel.score(X_test,y_test)

0.9574074074074074

In [33]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_trained_scaled = scaler.fit_transform(X_train)
X_test_scaled =  scaler.fit_transform(X_test)


In [34]:
from sklearn.svm import SVC
svm_model = SVC(kernel="rbf",C=1.0, gamma="scale")
svm_model.fit(X_trained_scaled,y_train)
svm_model.score(X_test_scaled,y_test)

0.9648148148148148

In [35]:
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier()
rf_model.fit(X_train,y_train)
rf_model.score(X_test,y_test)

0.9629629629629629

In [47]:
from sklearn.model_selection import cross_val_score
from numpy import mean
cross_val_score(LogisticRegression(max_iter=1000),digits.data,digits.target,cv=5, scoring='accuracy')

array([0.92222222, 0.86944444, 0.94150418, 0.94150418, 0.89693593])

In [48]:
mean(cross_val_score(LogisticRegression(max_iter=1000),digits.data,digits.target,cv=5, scoring='accuracy'))

np.float64(0.914322191272052)

In [41]:
from sklearn.model_selection import cross_val_score
cross_val_score(SVC(),digits.data,digits.target,cv=5, scoring='accuracy')

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [49]:
mean(cross_val_score(SVC(),digits.data,digits.target,cv=5, scoring='accuracy'))

np.float64(0.9632838130609718)

In [50]:
from sklearn.model_selection import cross_val_score
cross_val_score(RandomForestClassifier(),digits.data,digits.target,cv=5, scoring='accuracy')

array([0.93611111, 0.91111111, 0.9637883 , 0.96100279, 0.93036212])

In [51]:
mean(cross_val_score(RandomForestClassifier(),digits.data,digits.target,cv=5, scoring='accuracy'))

np.float64(0.9349102445063447)