In [1]:
from sklearn.datasets import load_iris
iris = load_iris()

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(iris.data,iris.target,test_size=0.3)

In [5]:
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()
X_train_scaled = scalar.fit_transform(X_train)
y_train_scaled = scalar.fit_transform(X_test)

In [22]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
cross_val_score(LogisticRegression(max_iter=1000),iris.data,iris.target, cv=5,scoring="accuracy")

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [23]:
from numpy import mean
mean(cross_val_score(LogisticRegression(max_iter=1000),iris.data,iris.target, cv=5,scoring="accuracy"))

np.float64(0.9733333333333334)

In [33]:
# from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC
cross_val_score(SVC(kernel="linear", C = 1.0),iris.data,iris.target, cv=5,scoring="accuracy")

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [34]:
mean(cross_val_score(SVC(kernel="linear", C = 1.0),iris.data,iris.target, cv=5,scoring="accuracy"))

np.float64(0.9800000000000001)

In [35]:
from sklearn.ensemble import RandomForestClassifier
cross_val_score(RandomForestClassifier(),iris.data,iris.target,cv=5, scoring="accuracy")


array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [36]:
mean(cross_val_score(RandomForestClassifier(),iris.data,iris.target,cv=5, scoring="accuracy"))

np.float64(0.96)