In [2]:
from tensorflow import keras
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("insurance_data.csv")
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [4]:
X_train, X_test, y_train, y_test = train_test_split(df[["age","affordibility"]], df["bought_insurance"], test_size=0.2, random_state=42)

In [5]:
X_train.head()

age  affordibility
17   58              1
22   40              1
11   28              1
13   29              0
15   55              1

In [6]:
X_train_scaled =  X_train.copy()
X_train_scaled["age"] = X_train_scaled["age"]/100

X_test_scaled =  X_test.copy()
X_test_scaled["age"] = X_test_scaled["age"]/100

X_test_scaled.head()

age  affordibility
9   0.61              1
25  0.54              1
8   0.62              1
21  0.26              0
0   0.22              1

In [7]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,), activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train_scaled, y_train, epochs=5000)

Epoch 1/5000


C:\Users\niraj.meshram\AppData\Local\miniconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 566ms/step - accuracy: 0.5000 - loss: 0.7428
Epoch 2/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.7424
Epoch 3/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.7420
Epoch 4/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.7416
Epoch 5/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.7411
Epoch 6/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.7407
Epoch 7/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.7403
Epoch 8/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.7399
Epoch 9/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.7395
Epoch 10/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5000 - loss: 0.7390
Epoch 11/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.7386
Epoch 12/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - lo

In [62]:
model.evaluate(X_test_scaled,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 1.0000 - loss: 0.2647


[0.26470306515693665, 1.0]

In [8]:
X_test_scaled

age  affordibility
9   0.61              1
25  0.54              1
8   0.62              1
21  0.26              0
0   0.22              1
12  0.27              0

In [9]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step


array([[0.81626713],
       [0.7576754 ],
       [0.82367426],
       [0.18819508],
       [0.38559136],
       [0.19598217]], dtype=float32)

In [65]:
 coef, intercept = model.get_weights()
coef, intercept

(array([[5.018309 ],
        [1.1966311]], dtype=float32),
 array([-2.766541], dtype=float32))

In [28]:
def sigmoid(x):
    import math
    return 1 / ( 1 + math.exp(-x))

sigmoid(23)

0.9999999998973812

In [39]:
X_test

age  affordibility
9    61              1
25   54              1
8    62              1
21   26              0
0    22              1
12   27              0

In [31]:
coef[0]

array([5.018309], dtype=float32)

In [49]:
def predict_function(age, affordability):
    weighted_sum = coef[0]*age + coef[1] + intercept
    return sigmoid(weighted_sum)

predict_function(.26,0)

C:\Users\niraj.meshram\AppData\Local\Temp\ipykernel_3068\1602980499.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / ( 1 + math.exp(-x))


0.43409824809403247

In [52]:
def sigmoid_numpy(x):
    return 1/(1+np.exp(-x))
sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [53]:
def log_loss(y_truth, y_predict):
    epsilon = 1e-15
    y_predict_new = [max(i, epsilon) for i in y_predict]
    y_predict_new = [min(i, epsilon) for i in y_predict_new]
    y_predict_new = np.array(y_predict_new)
    return -np.mean(y_truth*np.log(y_predict_new)+(1-y_truth)*np.log(1-y_predict_new))
    

In [54]:

def gradient_descent(age, affordability, y_true, epochs, loss_thresold):
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age)
    for i in range(epochs):
        weighted_sum = w1 * age + w2 * affordability + bias
        y_predicted = sigmoid_numpy(weighted_sum)
        loss = log_loss(y_true, y_predicted)

        w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true)) 
        w2d = (1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true)) 

        bias_d = np.mean(y_predicted-y_true)
        w1 = w1 - rate * w1d
        w2 = w2 - rate * w2d
        bias = bias - rate * bias_d

        print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')

        if loss<=loss_thresold:
            break

    return w1, w2, bias

In [56]:
coef, intercept

(array([[5.018309 ],
        [1.1966311]], dtype=float32),
 array([-2.766541], dtype=float32))

In [66]:
################# Writing a custom class for gradient descent to which will traina model (fit method ) and predit the Insurance #################

In [112]:
customModel = myNN()
customModel.fit(X_train_scaled, y_train, epochs = 500, loss_threshold = 0.4631)

Epoch:0, w1:0.9736899318847281, w2:0.931388810977659, bias:-0.11748951666770448, loss:17.26938819745534
Epoch:1, w1:0.9536535852311093, w2:0.8740290167758512, bias:-0.21881533456146035, loss:17.26938819745534
Epoch:2, w1:0.9393731039296968, w2:0.8271852202997496, bias:-0.3053620401943441, loss:17.26938819745534
Epoch:3, w1:0.930193258899806, w2:0.7897792032048467, bias:-0.37884372361582785, loss:17.26938819745534
Epoch:4, w1:0.9254091137248937, w2:0.7605726653866934, bias:-0.441082368200183, loss:17.26938819745534
Epoch:5, w1:0.9243325693598606, w2:0.738313053647322, bias:-0.4938425798625155, loss:17.26938819745534
Epoch:6, w1:0.9263332963572349, w2:0.7218280753843739, bias:-0.5387319906498417, loss:17.26938819745534
Epoch:7, w1:0.9308580975636879, w2:0.7100747303660235, bias:-0.5771558825717441, loss:17.26938819745534
Epoch:8, w1:0.9374354910317361, w2:0.7021560855322683, bias:-0.6103083840841516, loss:17.26938819745534
Epoch:9, w1:0.9456716791005844, w2:0.6973185496313956, bias:-0.63

In [107]:
class myNN:
    def __init__(self):
        self.w1 = 1
        self.w2 = 1
        self.bias =0

    def fit(self, X, y, epochs, loss_threshold):
        self.w1, self.w2, self.bias = self.gradient_descent(X["age"],X["affordibility"],y,epochs,loss_threshold)
    
    def predicted(self, X_test):
        weighted_sum =  self.w1 * X_test["age"] + self.w2 * X_test["affordibility"] + self.bias
        return sigmoid_numpy(weighted_sum)
    
    def gradient_descent(self, age, affordability, y_true, epochs, loss_threshold):
        w1 = w2 = 1
        bias = 0
        rate = 0.5
        n = len(age)

        for i in range(epochs):
            weighted_sum = w1 * age + w2 * affordability + bias
            y_predicted =  sigmoid_numpy(weighted_sum)
            loss = log_loss(y_true, y_predicted)

            w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true))
            w2d = (1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true))

            bias_d =  np.mean(y_predicted-y_true)

            w1 = w1 - rate * w1d
            w2 = w2 - rate * w2d
            bias =  bias - rate*bias_d

            print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
            if loss<=loss_threshold:
                break

        return w1, w2, bias

In [113]:
customModel.predicted(X_test_scaled)

9     0.848738
25    0.785705
8     0.856377
21    0.154336
0     0.343904
12    0.162438
dtype: float64

In [114]:
gradient_descent(X_train_scaled['age'],X_train_scaled['affordibility'],y_train,1000, 0.4631)

Epoch:0, w1:0.9736899318847281, w2:0.931388810977659, bias:-0.11748951666770448, loss:17.26938819745534
Epoch:1, w1:0.9536535852311093, w2:0.8740290167758512, bias:-0.21881533456146035, loss:17.26938819745534
Epoch:2, w1:0.9393731039296968, w2:0.8271852202997496, bias:-0.3053620401943441, loss:17.26938819745534
Epoch:3, w1:0.930193258899806, w2:0.7897792032048467, bias:-0.37884372361582785, loss:17.26938819745534
Epoch:4, w1:0.9254091137248937, w2:0.7605726653866934, bias:-0.441082368200183, loss:17.26938819745534
Epoch:5, w1:0.9243325693598606, w2:0.738313053647322, bias:-0.4938425798625155, loss:17.26938819745534
Epoch:6, w1:0.9263332963572349, w2:0.7218280753843739, bias:-0.5387319906498417, loss:17.26938819745534
Epoch:7, w1:0.9308580975636879, w2:0.7100747303660235, bias:-0.5771558825717441, loss:17.26938819745534
Epoch:8, w1:0.9374354910317361, w2:0.7021560855322683, bias:-0.6103083840841516, loss:17.26938819745534
Epoch:9, w1:0.9456716791005844, w2:0.6973185496313956, bias:-0.63

(8.40135186247223, 1.5008804215445, -4.382056927000267)